### ISSUE TITLE
restart-required: command fails after an exporter.yml change 

### ISSUE THREAD

**Issue by mehdibn** [TOSIT-IO/tdp-lib#230]
This command fails only with the first element of the list (exporter in our case)

**Test Scenario:**

-  add a comment to `vars/exporter/exporter.yml`
-  commit change 
-  execute `tdp restart-required --dry`

**Execution Error:** 
```
2022-10-04 15:38:50,591 - DEBUG - tdp.<module> - Logger initialized
Traceback (most recent call last):
  File "/home/diode-ben-aissa01/dev/tdp-lib/tdp/core/runner/operation_runner.py", line 30, in __next__
    operation_log = next(self._operations)
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/diode-ben-aissa01/dev/tdp-lib/venv/bin/tdp", line 5, in <module>
    tdp()
  File "/home/diode-ben-aissa01/dev/tdp-lib/venv/lib/python3.6/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/diode-ben-aissa01/dev/tdp-lib/venv/lib/python3.6/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/diode-ben-aissa01/dev/tdp-lib/venv/lib/python3.6/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/diode-ben-aissa01/dev/tdp-lib/venv/lib/python3.6/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/diode-ben-aissa01/dev/tdp-lib/venv/lib/python3.6/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/diode-ben-aissa01/dev/tdp-lib/tdp/cli/commands/restart_required.py", line 103, in restart_required
    for operation in operation_iterator:
  File "/home/diode-ben-aissa01/dev/tdp-lib/tdp/core/runner/operation_runner.py", line 34, in __next__
    self.fill_deployment_log_at_end()
  File "/home/diode-ben-aissa01/dev/tdp-lib/tdp/core/runner/operation_runner.py", line 43, in fill_deployment_log_at_end
    state if state else self.deployment_log.operations[-1].state
IndexError: list index out of range
```

**Comment by gboutry** [comment]
https://github.com/TOSIT-IO/tdp-lib/pull/221 should have fixed this issue, are you up to date ?

**Comment by mehdibn** [comment]
> #221 should have fixed this issue, are you up to date ?

yes

**Comment by gboutry** [comment]
Ok, this is actually an edge case, where all actions returned by `restart-required` are noops. I will upload a fix
