### ISSUE TITLE
sqlalchemy.exc.MultipleResultsFound when qureying the log of an operaion involving several hosts

### ISSUE THREAD

**Issue by mdrutel** [TOSIT-IO/tdp-lib#453]
Hi,

When I try to display the operation log exectuted on multiple hosts, I have an error.
Eg. : the operation ```hive_hiveserver2_restart``` was executed on 2 hosts : server01 and server02 :

```
              2                 65  hive_hiveserver2_restart                   server01                                          PLANNED
              2                 66  hive_hiveserver2_restart                   server02                                          PLANNED
```
When I want to display the log, I have a ```sqlalchemy.exc.MultipleResultsFound``` exception :

```
$ tdp browse 2 hive_hiveserver2_restart
2023-10-10 15:22:38,363 - DEBUG - tdp.<module> - Logger initialized
Traceback (most recent call last):
  File "/home/mdrutel01/projets/git/tdp-ops/venv/bin/tdp", line 6, in <module>
    sys.exit(tdp())
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/click/core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "/home/mdrutel01/projets/git/tdp-ops/tdp/tdp-lib/tdp/cli/commands/browse.py", line 64, in browse
    _print_operation(get_operation_log(session, deployment_id, operation))
  File "/home/mdrutel01/projets/git/tdp-ops/tdp/tdp-lib/tdp/cli/queries.py", line 436, in get_operation_log
    session.query(OperationLog)
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/sqlalchemy/orm/query.py", line 2797, in one
    return self._iter().one()  # type: ignore
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 1827, in one
    return self._only_one_row(
  File "/home/mdrutel01/projets/git/tdp-ops/venv/lib/python3.9/site-packages/sqlalchemy/engine/result.py", line 813, in _only_one_row
    raise exc.MultipleResultsFound(
sqlalchemy.exc.MultipleResultsFound: Multiple rows were found when exactly one was required
```

**Comment by PaulFarault** [comment]
Thx! I'll fix it asap
